[RR]Update README.md
OpenLake/ProxyMan pull request #2
Opened 2021-06-08 07:52 UTC by Ananyaiitbhilai

created a section named how to create a PR - tells about step-by-step procedure about creating a PR

2021-06-11 18:59 UTC, yatendra1999 requested changes

2021-06-11 18:59 UTC, yatendra1999 commented on README.md
> +**#**  Take a look at the existing or create your own issues. A first good issue can be updating README file. Since Open Lake maintainers are generous enough, it is optional to create a issue or wait
Hmm. We are not generous in the least. LOL. Issues in my opinion are used for planned changes or mostly for bug reports from people who use the project. Also there are tags for good first issues, so you can just tell them to view by tags at first.

2021-06-11 18:59 UTC, yatendra1999 commented on README.md
> +**10.** Track your changes .
Tracked and untracked changes are different. They usually refer to what github sees and what it ignores using .gitignore. The correct term would be staging the changes.

2021-06-11 19:00 UTC, yatendra1999 commented
GIFs were good. LOL

2021-06-11 19:04 UTC, yatendra1999 commented on README.md
> +**14.** Add appropriate title and description to your pull request explaining your changes. You can see the official PR Format Guidelines [here](https://github.com/OpenLake/Leaderboard-Pro/wiki/PR-Fo
That is the format for that repo, this project doesn't have one and I am fine with people including only the necessary stuff like listing the changes made and adding a meaningful heading reflecting the changes.

2021-06-11 19:07 UTC, yatendra1999 commented
The same review is valid for your PR in the other repo as well. But this information usually resides in wiki pages. 
Also I would suggest you to try and make changes other than readme.

2021-06-12 12:16 UTC, Ananyaiitbhilai commented on README.md
> +**#**  Take a look at the existing or create your own issues. A first good issue can be updating README file. Since Open Lake maintainers are generous enough, it is optional to create a issue or wait
done

2021-06-12 12:17 UTC, Ananyaiitbhilai commented on README.md
> +**10.** Track your changes .
done

2021-06-12 12:17 UTC, Ananyaiitbhilai commented on README.md
> +**14.** Add appropriate title and description to your pull request explaining your changes. You can see the official PR Format Guidelines [here](https://github.com/OpenLake/Leaderboard-Pro/wiki/PR-Fo
done

2021-06-12 12:33 UTC, Ananyaiitbhilai commented
> The same review is valid for your PR in the other repo as well. But this information usually resides in wiki pages.
> Also I would suggest you to try and make changes other than readme.

ok, in code contributors section of readme, i have added the link to wiki. So if feasible, u can add the instruction about creating a PR in wiki and then the wiki link would be provided in readme.
I would try but a major problem is that I have never worked with flutter previously and if a basic workflow diagram was there it would be better and there are hundreds of new words , that I have never encountered ever before. Even I didn't know about the proxy managers, its use until I saw this project

2021-06-13 05:34 UTC, yatendra1999 approved these changes

2021-06-13 05:38 UTC, yatendra1999 commented
> I would try but a major problem is that I have never worked with flutter previously and if a basic workflow diagram was there it would be better and there are hundreds of new words , that I have never encountered ever before. Even I didn't know about the proxy managers, its use until I saw this project
Most projects will have a steep learning curve right at the start. If you have any issues just contact people and ask them about it. This goes for all projects. You don't need to understand it all on your own and we don't expect you to.

2021-06-13 05:38 UTC, merged